title: Sublayer Docs
description: A model agnostic AI agent framework in Ruby
theme: just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true
url: "https://docs.sublayer.com"
logo: "/assets/images/sublayer-logo-transparent@2x.png"
favicon_ico: "/assets/images/favicon.png"

aux_links:
  Sublayer Gem: https://github.com/sublayerapp/sublayer
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/sublayerapp/sublayer_documentation"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"

ga_tracking: "G-05P9NYF7YV"

footer_content: "Copyright &copy; 2024 Sublayer, Inc. All rights reserved."
